package io.openems.edge.ess.solarwatt.myreserve.meter;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.meter.api.MeterType;
import io.openems.edge.meter.api.SinglePhase;

@ObjectClassDefinition(//
		name = "ESS Solarwatt MyReserve VirtualMeter Singlephase", //
		description = "Implements a Solarwatt Virtual singlephase meter. ")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "meter0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Phase", description = "Phase measured by this Meter.")
	SinglePhase phase() default SinglePhase.L1;

	@AttributeDefinition(name = "Meter-Type", description = "Meter-Type of this Meter.")
	MeterType type() default MeterType.PRODUCTION;

	@AttributeDefinition(name = "Battery ID", description = "ID of the solarwatt myreserve battery Component.")
	String battery_id() default "sw0";
	
	@AttributeDefinition(name = "Battery target filter", description = "This is auto-generated by 'Core ID'.")
	String battery_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "ESS Solarwatt MyReserve Virtual Meter Singlephase [{id}]";

}