package io.openems.edge.ess.sennec.home.enums;

//copied from https://github.com/nobl/ioBrokersenec/blob/master/lib/mode_descjs

public enum SennecHomeState {

	INITIALZUSTAND(0), 
	KEINE_KOMMUNIKATION_LADEGERAET(1), 
	FEHLER_LEISTUNGSMESSGERAET(2),
	RUNDSTEUEREMPFAENGER(3),
	ERSTLADUNG(4), 
	WARTUNGSLADUNG(5), 
	WARTUNGSLADUNG_FERTIG(6), 
	WARTUNG_NOTWENDIG(7), 
	MAN_SICHERHEITSLADUNG(8),
	SICHERHEITSLADUNG_FERTIG(9), 
	VOLLLADUNG(10), 
	AUSGLEICHSLADUNG_LADEN(11), 
	SULFATLADUNG_LADEN(12), 
	AKKU_VOLL(13),
	LADEN(14), 
	AKKU_LEER(15), 
	ENTLADEN(16), 
	PV_UND_ENTLADEN(17), 
	NETZ_UND_ENTLADEN(18), 
	PASSIV(19), 
	AUSGESCHALTET(20),
	EIGENVERBRAUCH(21), 
	NEUSTART(22), 
	MAN_AUSGLEICHSLADUNG_LADEN(23), 
	MAN_SULFATLADUNG_LADEN(24), 
	SICHERHEITSLADUNG(25),
	AKKU_SCHUTZBETRIEB(26), 
	EG_FEHLER(27), 
	EG_LADEN(28), 
	EG_ENTLADEN(29), 
	EG_PASSIV(30), 
	EG_LADEN_VERBOTEN(31),
	EG_ENTLADEN_VERBOTEN(32), 
	NOTLADUNG(33), SOFTWAREAKTUALISIERUNG(34), 
	FEHLER_NA_SCHUTZ(35),
	FEHLER_NA_SCHUTZ_NETZ(36), 
	FEHLER_NA_SCHUTZ_HARDWARE(37), 
	KEINE_SERVERVERBINDUNG(38), 
	BMS_FEHLER(39),
	WARTUNG_FILTER(40), 
	SCHLAFMODUS(41), 
	WARTE_AUF_UEBERSCHUSS(42), 
	KAPAZITAETSTEST_LADEN(43),
	KAPAZITAETSTEST_ENTLADEN(44), 
	MAN_SULFATLADUNG_WARTEN(45), 
	MAN_SULFATLADUNG_FERTIG(46), 
	MAN_SULFATLADUNG_FEHLER(47),
	AUSGLEICHSLADUNG_WARTEN(48), 
	NOTLADUNG_FEHLER(49), 
	MAN_AUSGLEICHSLADUNG_WARTEN(50), 
	MAN_AUSGLEICHSLADUNG_FEHLER(51),
	MAN_AUSGLEICHSLADUNG_FERTIG(52), 
	AUTO_SULFATLADUNG_WARTEN(53), 
	LADESCHLUSSPHASE(54), 
	BATTERIETRENNSCHALTER_AUS(55),
	PEAK_SHAVING_WARTEN(56), 
	FEHLER_LADEGERAET(57), 
	NPU_FEHLER(58), 
	BMS_OFFLINE(59), 
	WARTUNGSLADUNG_FEHLER(60),
	MAN_SICHERHEITSLADUNG_FEHLER(61), 
	SICHERHEITSLADUNG_FEHLER(62), 
	KEINE_MASTERVERBINDUNG(63),
	LITHIUM_SICHERHEITSMODUS_AKTIV(64), 
	LITHIUM_SICHERHEITSMODUS_BEENDET(65), 
	FEHLER_BATTERIESPANNUNG(66),
	BMS_DC_AUSGESCHALTET(67), 
	NETZINITIALISIERUNG(68), 
	NETZSTABILISIERUNG(69), 
	FERNABSCHALTUNG(70), 
	OFFPEAK_LADEN(71),
	FEHLER_HALBBRUECKE(72), 
	INITIALISIERUNG(78), 
	INSTALLATIONSMODUS(79), 
	NETZAUSFALL(80), 
	BMS_UPDATE_ERFORDERLICH(81),
	BMS_KONFIGURATION_ERFORDERLICH(82), 
	ISOLATIONSTEST(83), 
	SELBSTTEST(84), 
	EXTERNE_STEUERUNG(85);

	private final int id;

	private SennecHomeState(int id) {
		this.id = id;
	}

	/**
	 * Gets the id of the state.
	 * 
	 * @return the id of the state
	 */

	public int getId() {
		return this.id;
	}

}
