package io.openems.edge.ess.sennec.home.meter.three;

import org.osgi.service.metatype.annotations.AttributeDefinition;
import org.osgi.service.metatype.annotations.ObjectClassDefinition;

import io.openems.edge.meter.api.MeterType;

@ObjectClassDefinition(//
		name = "ESS Sennec Home Virtual Meter Threephase", //
		description = "Implements a Sennec Home Virtual Meter Threephase meter. ")
@interface Config {

	@AttributeDefinition(name = "Component-ID", description = "Unique ID of this Component")
	String id() default "meter0";

	@AttributeDefinition(name = "Alias", description = "Human-readable name of this Component; defaults to Component-ID")
	String alias() default "";

	@AttributeDefinition(name = "Is enabled?", description = "Is this Component enabled?")
	boolean enabled() default true;

	@AttributeDefinition(name = "Meter-Type", description = "Meter-Type of this Meter (only provides the meter types GRID).")
	MeterType type() default MeterType.GRID;

	@AttributeDefinition(name = "Battery ID", description = "ID of the sennec battery Component.")
	String battery_id() default "senec0";

	@AttributeDefinition(name = "Battery target filter", description = "This is auto-generated by 'Core ID'.")
	String battery_target() default "(enabled=true)";

	String webconsole_configurationFactory_nameHint() default "ESS Sennec Home Virtual Meter Threephase [{id}]";

}